import { Metadata } from "next";
import "../styles/global.scss";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
//const inter = Inter({ subsets: ["latin"], display: "swap" });

const font = localFont({
  src: [
    {
      path: "../fonts/TTNorms-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/TTNorms-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/TTNorms-ExtraBold.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../fonts/TTNorms-Bold.woff",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
});

// bold, extraBold, medium, regular

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // icons: {
  //   href: ''
  // }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={font.className}>{children}</body>
    </html>
  );
}
